### ISSUE TITLE
Flexible array member in CPP output

### ISSUE THREAD

**Issue by syoyo** [KhronosGroup/SPIRV-Cross#10]
Flexible array member is not supported in C++11 http://stackoverflow.com/questions/4412749/are-flexible-array-members-valid-in-c

Thus the following generated CPP code is failed to compile with clang 3.8.
 
```
// (c++ code generated from basic.comp example)
namespace Impl
{
    struct Shader
    {
        struct Resources : ComputeResources
        {
            struct SSBO
            {
                vec4 in_data[];
            };
```

```
basic-shader.cc:17:22: error: flexible array member 'in_data' of type 'vec4 []' with non-trivial destruction
                vec4 in_data[];
```

Possible solution is to use pointer representation(`vec4 *in_data`), but this will require manual update  `PreDereference` flag in PointerInterface class.

**Comment by HansKristian-ARM** [comment]
Hm, this does work with Clang/C++ (albeit via language extension), but it is not standard conforming in C++11 indeed.

Instead of going with a pointer, the usual workaround for this is to have a vec4 in_data[1] member. I think I'd rather lean towards that since the fix is trivial to implement and less likely to go wrong.

**Comment by syoyo** [comment]
>  so having [1] should be fine.

Thanks! It works like a charm. And here's PR to avoid emitting flexible array member in C++ codegen:  https://github.com/KhronosGroup/SPIRV-Cross/pull/13

**Comment by HansKristian-ARM** [comment]
Fixed on master.
