### ISSUE TITLE
Compilation error (stringop-overflow error)

### ISSUE THREAD

**Issue by shinchiro** [KhronosGroup/SPIRV-Cross#951]
I'm trying to to cross-compile on mingw-w64+gcc8.3.1 but got some error. Hope you can look at it. 

https://0x0.st/zqDg.log

**Comment by DeadSix27** [comment]
I have the same issue, works fine with -O2. 
I've built on Arch using GCC snapshot v8-20190329 and MinGW git master.

Both GCC and MinGW are compiled by myself and not prebuilt. Do you need the exact build options?

**Comment by HansKristian-Work** [comment]
Ok, I can reproduce the warning on Linux GCC with -O3 as well.
