### PR TITLE
MSL: fix function constant deduplication misfire

### PR DESCRIPTION
**Pull request by rcombs**
Previously, if a constant without `DecorationSpecId` occurred before the constant with `DecorationSpecId` 0, it would be inserted into the `unique_func_constants` map with key 0 (the default return value from `get_decoration`). This prevented us from ever emitting the declaration with `[[function_constant(0)]]`, which produced some bizarre MSL compilation errors.

Instead, we now only insert into `unique_func_constants` when we know we're going to emit a `[[function_constant(…)]]` line.

This regressed in 41007cdc7d9c3a1f9b61e307d149f94a68fa3c9c.

### CODE REVIEW

**Review by HansKristian-Work — APPROVED** [review]
LGTM if CI passes.
