### ISSUE TITLE
MSVC Compiler Warning

### ISSUE THREAD

**Issue by manaskulkarni786** [KhronosGroup/SPIRV-Cross#1068]
I am getting compiler warnings on Visual Studio version 15.6. It works fine on Visual Studio version 15.9 but we have some people using 15.6. The warning message appears in both latest from master and the latest release.

Warning:

> >c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.13.26128\include\xutility(2830): error C2220: warning treated as error - no 'object' file generated (compiling source file spirv_glsl.cpp)
3>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.13.26128\include\xutility(2830): warning C4996: 'std::move_backward::_Unchecked_iterators::_Deprecate': Call to 'std::move_backward' with parameters that may be unsafe - this call relies on the caller to check that the passed values are correct. To disable this warning, use -D_SCL_SECURE_NO_WARNINGS. See documentation on how to use Visual C++ 'Checked Iterators' (compiling source file spirv_glsl.cpp)
3>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.13.26128\include\xutility(2830): note: see declaration of 'std::move_backward::_Unchecked_iterators::_Deprecate' (compiling source file spirv_glsl.cpp)
3>spirv_cross_containers.hpp(431): note: see reference to function template instantiation '_BidIt2 std::move_backward<T*,T*>(_BidIt1,_BidIt1,_BidIt2)' being compiled
3>

**Comment by manaskulkarni786** [comment]
Doesn't really fix it for people not using CMAKE

**Comment by HansKristian-Work** [comment]
I tried fixing it with pragmas, but it does not work apparently. I only see MSVC 2015 output through AppVeyor and iterating on these things take forever. Please either add /wd4996 yourself to your custom build system, /D_SCL_SECURE_NO_WARNINGS or propose a PR with the fix.
